import type { AuditLog } from "@/lib/types/audit.types";

export const seedAuditLogs: AuditLog[] = [
  {
    id: "aud_001",
    action: "UPDATE_PRIORITY",
    entity: "EmergencyRequest",
    entityId: "em_001",
    performedBy: "usr_disp_01",
    performedByRole: "DISPATCHER",
    performedByName: "Kazi Nabil",
    ipAddress: "103.230.104.12",
    oldData: { priority: null, status: "PENDING" },
    newData: { priority: "P1_CRITICAL", status: "PRIORITIZED" },
    createdAt: "2026-03-26T14:15:30.000Z",
  },
  {
    id: "aud_002",
    action: "CREATE_DISPATCH",
    entity: "Dispatch",
    entityId: "disp_001",
    performedBy: "usr_disp_01",
    performedByRole: "DISPATCHER",
    performedByName: "Kazi Nabil",
    ipAddress: "103.230.104.12",
    oldData: null,
    newData: {
      emergencyId: "em_001",
      ambulanceId: "amb_001",
      driverId: "drv_001",
      status: "PENDING_ACCEPTANCE",
      timeoutAt: "2026-03-26T14:18:00.000Z",
    },
    createdAt: "2026-03-26T14:16:00.000Z",
  },
  {
    id: "aud_003",
    action: "UPDATE_USER_STATUS",
    entity: "User",
    entityId: "usr_patient_02",
    performedBy: "usr_admin_01",
    performedByRole: "ADMIN",
    performedByName: "Farhana Yasmin",
    ipAddress: "103.230.104.5",
    oldData: { status: "ACTIVE" },
    newData: {
      status: "SUSPENDED",
      reason: "Repeated non-emergency false dispatch reports",
    },
    createdAt: "2026-03-01T12:00:00.000Z",
  },
  {
    id: "aud_004",
    action: "CANCEL_DISPATCH",
    entity: "Dispatch",
    entityId: "disp_005",
    performedBy: "usr_disp_01",
    performedByRole: "DISPATCHER",
    performedByName: "Kazi Nabil",
    ipAddress: "103.230.104.12",
    oldData: { status: "PENDING_ACCEPTANCE" },
    newData: {
      status: "CANCELLED",
      reason: "Caller reported patient was transported privately",
    },
    createdAt: "2026-03-26T13:48:30.000Z",
  },
  {
    id: "aud_005",
    action: "UPDATE_PRIORITY",
    entity: "EmergencyRequest",
    entityId: "em_003",
    performedBy: "usr_disp_01",
    performedByRole: "DISPATCHER",
    performedByName: "Kazi Nabil",
    ipAddress: "103.230.104.12",
    oldData: { priority: null, status: "PENDING" },
    newData: { priority: "P2_EMERGENCY", status: "PRIORITIZED" },
    createdAt: "2026-03-26T14:36:00.000Z",
  },
  {
    id: "aud_006",
    action: "UPDATE_HOSPITAL_DIVERSION",
    entity: "Hospital",
    entityId: "hosp_003",
    performedBy: "usr_admin_01",
    performedByRole: "ADMIN",
    performedByName: "Farhana Yasmin",
    ipAddress: "103.230.104.5",
    oldData: { diversionStatus: "ACCEPTING" },
    newData: { diversionStatus: "DIVERTING", reason: "ER near full capacity" },
    createdAt: "2026-03-26T14:25:00.000Z",
  },
];
