import type { EmergencyRequest } from "@/lib/types/emergency.types";
import {
  EmergencyPriority,
  EmergencyStatus,
  EmergencyType,
  RequiredCapability,
} from "@/lib/types/enums";

export const seedEmergencies: EmergencyRequest[] = [
  {
    id: "em_001",
    incidentNumber: "INC-2026-000001",
    patientId: "usr_patient_01",
    emergencyType: EmergencyType.CARDIAC,
    requiredCapability: RequiredCapability.ALS,
    priority: EmergencyPriority.P1_CRITICAL,
    status: EmergencyStatus.ACTIVE_TRIP,
    description:
      "58yo male experiencing severe retrosternal chest pain radiating to left jaw, diaphoresis.",
    locationAddress: "House 24, Road 11, Banani, Dhaka-1213",
    locationLat: 23.7937,
    locationLng: 90.4066,
    callerName: "Tanvir Hasan",
    callerPhone: "+8801711555555",
    isEscalated: false,
    escalationReason: null,
    slaTargetMinutes: 8,
    responseTimeMinutes: 6.2,
    cancelledAt: null,
    cancellationReason: null,
    cancelledBy: null,
    createdAt: "2026-03-26T14:15:00.000Z",
    updatedAt: "2026-03-26T14:22:00.000Z",
  },
  {
    id: "em_002",
    incidentNumber: "INC-2026-000002",
    patientId: "usr_patient_02",
    emergencyType: EmergencyType.TRAUMA,
    requiredCapability: RequiredCapability.ALS,
    priority: EmergencyPriority.P1_CRITICAL,
    status: EmergencyStatus.DISPATCHING,
    description:
      "High speed motor vehicle collision. Multiple casualties, active head trauma with bleeding.",
    locationAddress: "Kuril Flyover Ramp, Progoti Shoroni, Dhaka",
    locationLat: 23.8151,
    locationLng: 90.4255,
    callerName: "Inspector Rashed",
    callerPhone: "+8801712000011",
    isEscalated: true,
    escalationReason: "Multiple critical victims at scene",
    slaTargetMinutes: 8,
    responseTimeMinutes: null,
    cancelledAt: null,
    cancellationReason: null,
    cancelledBy: null,
    createdAt: "2026-03-26T14:30:00.000Z",
    updatedAt: "2026-03-26T14:32:00.000Z",
  },
  {
    id: "em_003",
    incidentNumber: "INC-2026-000003",
    patientId: "usr_patient_03",
    emergencyType: EmergencyType.RESPIRATORY,
    requiredCapability: RequiredCapability.BLS,
    priority: EmergencyPriority.P2_EMERGENCY,
    status: EmergencyStatus.PRIORITIZED,
    description:
      "Acute severe asthma exacerbation, patient unable to complete sentences, SpO2 88%.",
    locationAddress: "Sector 4, Road 7, Uttara, Dhaka-1230",
    locationLat: 23.8682,
    locationLng: 90.3984,
    callerName: "Dr. Laila Parveen",
    callerPhone: "+8801712000022",
    isEscalated: false,
    escalationReason: null,
    slaTargetMinutes: 12,
    responseTimeMinutes: null,
    cancelledAt: null,
    cancellationReason: null,
    cancelledBy: null,
    createdAt: "2026-03-26T14:35:00.000Z",
    updatedAt: "2026-03-26T14:36:00.000Z",
  },
  {
    id: "em_004",
    incidentNumber: "INC-2026-000004",
    patientId: "usr_patient_04",
    emergencyType: EmergencyType.OBSTETRIC,
    requiredCapability: RequiredCapability.NEONATAL,
    priority: EmergencyPriority.P2_EMERGENCY,
    status: EmergencyStatus.PENDING,
    description:
      "Pre-term labor at 31 weeks with premature rupture of membranes.",
    locationAddress: "Block D, Lalmatia, Dhaka-1207",
    locationLat: 23.7547,
    locationLng: 90.3704,
    callerName: "Khadija Begum",
    callerPhone: "+8801712000033",
    isEscalated: false,
    escalationReason: null,
    slaTargetMinutes: 12,
    responseTimeMinutes: null,
    cancelledAt: null,
    cancellationReason: null,
    cancelledBy: null,
    createdAt: "2026-03-26T14:40:00.000Z",
    updatedAt: "2026-03-26T14:40:00.000Z",
  },
  {
    id: "em_005",
    incidentNumber: "INC-2026-000005",
    patientId: "usr_patient_05",
    emergencyType: EmergencyType.NEUROLOGICAL,
    requiredCapability: RequiredCapability.ALS,
    priority: EmergencyPriority.P1_CRITICAL,
    status: EmergencyStatus.COMPLETED,
    description:
      "Sudden onset right-sided hemiplegia and expressive aphasia within last 45 minutes.",
    locationAddress: "Road 27, Dhanmondi, Dhaka-1209",
    locationLat: 23.7509,
    locationLng: 90.3755,
    callerName: "Ahsan Habib",
    callerPhone: "+8801712000044",
    isEscalated: false,
    escalationReason: null,
    slaTargetMinutes: 8,
    responseTimeMinutes: 7.5,
    cancelledAt: null,
    cancellationReason: null,
    cancelledBy: null,
    createdAt: "2026-03-26T11:00:00.000Z",
    updatedAt: "2026-03-26T12:15:00.000Z",
  },
  {
    id: "em_006",
    incidentNumber: "INC-2026-000006",
    patientId: "usr_patient_06",
    emergencyType: EmergencyType.PEDIATRIC,
    requiredCapability: RequiredCapability.BLS,
    priority: EmergencyPriority.P3_URGENT,
    status: EmergencyStatus.REASSIGNMENT_REQUIRED,
    description: "3yo child with febrile convulsions, temperature 103.5 F.",
    locationAddress: "Avenue 1, Mirpur DOHS, Dhaka",
    locationLat: 23.8341,
    locationLng: 90.3667,
    callerName: "Fatema Tuz Zohra",
    callerPhone: "+8801712000055",
    isEscalated: false,
    escalationReason: null,
    slaTargetMinutes: 20,
    responseTimeMinutes: null,
    cancelledAt: null,
    cancellationReason: null,
    cancelledBy: null,
    createdAt: "2026-03-26T13:50:00.000Z",
    updatedAt: "2026-03-26T14:10:00.000Z",
  },
  {
    id: "em_007",
    incidentNumber: "INC-2026-000007",
    patientId: "usr_patient_07",
    emergencyType: EmergencyType.OTHER,
    requiredCapability: RequiredCapability.BARIATRIC,
    priority: EmergencyPriority.P4_NON_URGENT,
    status: EmergencyStatus.CANCELLED,
    description:
      "Scheduled non-emergent bariatric transport for routine dialysis.",
    locationAddress: "Plot 12, Block C, Bashundhara R/A, Dhaka",
    locationLat: 23.8191,
    locationLng: 90.4358,
    callerName: "Mirza Galib",
    callerPhone: "+8801712000066",
    isEscalated: false,
    escalationReason: null,
    slaTargetMinutes: 45,
    responseTimeMinutes: null,
    cancelledAt: "2026-03-26T14:05:00.000Z",
    cancellationReason: "Patient arranged alternative family vehicle.",
    cancelledBy: "usr_disp_01",
    createdAt: "2026-03-26T13:45:00.000Z",
    updatedAt: "2026-03-26T14:05:00.000Z",
  },
  {
    id: "em_008",
    incidentNumber: "INC-2026-000008",
    patientId: "usr_patient_08",
    emergencyType: EmergencyType.PSYCHIATRIC,
    requiredCapability: RequiredCapability.BLS,
    priority: EmergencyPriority.P5_ROUTINE,
    status: EmergencyStatus.PENDING,
    description:
      "Mild disorientation and anxiety in elderly patient, stable vitals.",
    locationAddress: "North Goran, Khilgaon, Dhaka",
    locationLat: 23.7533,
    locationLng: 90.4289,
    callerName: "Jahangir Alam",
    callerPhone: "+8801712000077",
    isEscalated: false,
    escalationReason: null,
    slaTargetMinutes: 60,
    responseTimeMinutes: null,
    cancelledAt: null,
    cancellationReason: null,
    cancelledBy: null,
    createdAt: "2026-03-26T14:42:00.000Z",
    updatedAt: "2026-03-26T14:42:00.000Z",
  },
];
